### PR TITLE
Add global host option

### PR DESCRIPTION
**Pull request by larryzhao**
Add a global host option to module `RailsEmoji`.

### CODE REVIEW

**Comment by yyclaw** [comment]
thx

**Comment by larryzhao** [comment]
Would you push a new version of the gem to RubyGems with this update? Then I could use the gem directly. :)

**Comment by yyclaw** [comment]
I did it, but failed. I'll try tomorrow.

**Comment by larryzhao** [comment]
Thanks

## 

Cheers ~

Larry

**Comment by yyclaw** [comment]
@larryzhao done!

**Pull request merged**
