### PR TITLE
use Set instead of Array for better performance

### PR DESCRIPTION
**Pull request by ursm**
``` ruby
Benchmark.bm do |x|
  x.report(RailsEmoji::EMOJI.class) { 1000000.times { 'foo'.emojify } }
end
```

```
       user     system      total        real
Array  1.850000   0.000000   1.850000 (  1.853771)
Array  1.880000   0.000000   1.880000 (  1.888836)
Array  1.850000   0.000000   1.850000 (  1.865625)

       user     system      total        real
Set  1.640000   0.000000   1.640000 (  1.653069)
Set  1.680000   0.000000   1.680000 (  1.694423)
Set  1.630000   0.000000   1.630000 (  1.631746)
```

only slightly improved :wink:

### CODE REVIEW

**Comment by yyclaw** [comment]
请问你对钓鱼岛事件有什么看法？承认 Aoi Sora 是世界的么？

**Comment by ursm** [comment]
I would like to talk about a code. I do not necessarily want to talk about politics.

**Comment by yyclaw** [comment]
:laughing: Just a joke!

Only a little improvement, but  it lets me write more nine letters `Set.new()` . Uneconomical.

**Comment by ursm** [comment]
Okay, you have a point there. Thanks.

**Comment by yyclaw** [comment]
Thanks for your pull request

**Pull request closed without merging**
